#!/usr/bin/env bash
# The script extends previous exercise command and shows line holding the bash word, this lets  you to easily get the PID of your Bash process
# You cannot use pgrep
# shellcheck disable=SC2009

./1-list_your_processes | grep "bash"
