#!/usr/bin/env bash
#Kills the infinty and beyong program using sigkill signal
#Get the pid of the program
id = $(pgrep "bash ./4-to_infinity_and_beyond" -f)

#stop the infinate process
if [ -n "$id" ]
 then 
	kill -15 "$id"
fi
^C
